### ISSUE TITLE
 unable to purchase "child" tickets

### ISSUE THREAD

**Issue by pitera05** [wayneclub/Ticket-Bot#1]
It works!  But unable to purchase "child" tickets, how to fix it? Thanks.

**Comment by wayneclub** [comment]
> It works! But unable to purchase "child" tickets, how to fix it? Thanks.

Fixed, select child ticket number on `user_config.toml`

```toml
[fields.THSRC.ticket]
adult = 0 # 全票
child = 1 # 孩童票 (6-11)
disabled = 0 # 愛心票
elder = 0 # 敬老票
college = 0  # 大學生票
```
